# Generated by Django 2.1 on 2018-08-24 10:19
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uiks', '0002_address_ikperson'),
        ('addreses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik_tree_id', models.BigIntegerField()),
                ('intid', models.CharField(max_length=100)),
                ('levelid', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('uik_num', models.IntegerField(null=True)),
                ('full_address', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('done_tree', models.BooleanField(default=False)),
                ('done_info', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='addreses.TreeItem')),
                ('uik_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uiks.Address')),
            ],
        ),
    ]
