# Generated by Django 2.1 on 2018-08-27 03:21

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('addreses', '0002_treeitem'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(
            sql='CREATE INDEX trgm_idx ON addreses_treeitem USING GIST (full_address gist_trgm_ops);'),
    ]
