version: '3'

services:
  db:
    image: mdillon/postgis:9.6-alpine
    environment:
      POSTGRES_PASSWORD: iddqd
  django:
    image: aduchi/parse_uiks:latest
    environment:
      - SECRET_KEY=29
      - DATABASE_URL=postgis://postgres:iddqd@db:5432/postgres
      - DEBUG=true
    depends_on:
      - db
    ports:
      - "8000:8000"
    expose:
      - "8000"
