[tool.poetry]
name = "parse_uiks"
version = "0.1.0"
description = ""
authors = ["Artem Kanarev <aduchimergen@gmail.com>"]

[tool.poetry.dependencies]
python = "3.6"
django = "^2.0"
django-extensions = "^2.0"

[tool.poetry.dev-dependencies]
