# Generated by Django 2.1 on 2018-08-24 10:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uiks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cikrf_id', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('reg_num', models.IntegerField()),
                ('done_tree', models.BooleanField(default=False)),
                ('done_info', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('uik_num', models.SmallIntegerField(null=True)),
                ('level', models.SmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('ik_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('ik_lat', models.FloatField(blank=True, null=True)),
                ('ik_lon', models.FloatField(blank=True, null=True)),
                ('ik_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('voteroom_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('voteroom_lat', models.FloatField(blank=True, null=True)),
                ('voteroom_lon', models.FloatField(blank=True, null=True)),
                ('voteroom_coord', django.contrib.gis.db.models.fields.PointField(db_index=True, null=True, srid=4326)),
                ('voteroom_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='uiks.Address')),
            ],
            options={
                'ordering': ['update_time'],
            },
        ),
        migrations.CreateModel(
            name='IkPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('recomend_by', models.CharField(max_length=400)),
                ('ik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uiks.Address')),
            ],
        ),
    ]
