from django.test import TestCase

suggestion1 = {
    'value': 'г Томск, ул Шевченко, д 20',
    'unrestricted_value': 'Томская обл, г Томск, ул Шевченко, д 20',
    'data': {
        'postal_code': '634021',
        'country': 'Россия',
        'region_fias_id': '889b1f3a-98aa-40fc-9d3d-0f41192758ab',
        'region_kladr_id': '7000000000000',
        'region_with_type': 'Томская обл',
        'region_type': 'обл',
        'region_type_full': 'область',
        'region': 'Томская',
        'area_fias_id': None,
        'area_kladr_id': None,
        'area_with_type': None,
        'area_type': None,
        'area_type_full': None,
        'area': None,
        'city_fias_id': 'e3b0eae8-a4ce-4779-ae04-5c0797de66be',
        'city_kladr_id': '7000000100000',
        'city_with_type': 'г Томск',
        'city_type': 'г',
        'city_type_full': 'город',
        'city': 'Томск',
        'city_area': None,
        'city_district_fias_id': None,
        'city_district_kladr_id': None,
        'city_district_with_type': None,
        'city_district_type': None,
        'city_district_type_full': None,
        'city_district': None,
        'settlement_fias_id': None,
        'settlement_kladr_id': None,
        'settlement_with_type': None,
        'settlement_type': None,
        'settlement_type_full': None,
        'settlement': None,
        'street_fias_id': 'f132f7da-24d6-4dc0-8c22-eb219874e33a',
        'street_kladr_id': '70000001000086800',
        'street_with_type': 'ул Шевченко',
        'street_type': 'ул',
        'street_type_full': 'улица',
        'street': 'Шевченко',
        'house_fias_id': '585ede2f-ce65-4afb-8177-eab4ceaa2c8d',
        'house_kladr_id': '7000000100008680064',
        'house_type': 'д',
        'house_type_full': 'дом',
        'house': '20',
        'block_type': None,
        'block_type_full': None,
        'block': None,
        'flat_type': None,
        'flat_type_full': None,
        'flat': None,
        'flat_area': None,
        'square_meter_price': None,
        'flat_price': None,
        'postal_box': None,
        'fias_id': '585ede2f-ce65-4afb-8177-eab4ceaa2c8d',
        'fias_code': '70000001000000008680064',
        'fias_level': '8',
        'fias_actuality_state': '0',
        'kladr_id': '7000000100008680064',
        'capital_marker': '3',
        'okato': '69401000000',
        'oktmo': '69701000001',
        'tax_office': '7017',
        'tax_office_legal': '7017',
        'timezone': None,
        'geo_lat': '56.4769509',
        'geo_lon': '84.9929262',
        'beltway_hit': None,
        'beltway_distance': None,
        'metro': None,
        'qc_geo': '0',
        'qc_complete': None,
        'qc_house': None,
        'history_values': None,
        'unparsed_parts': None,
        'source': 'томск шевчеко 20',
        'qc': None
    }
}
suggestion2 = {
    'value': 'Томская обл, Томский р-н, село Турунтаево, ул Октябрьская',
    'unrestricted_value': 'Томская обл, Томский р-н, село Турунтаево, ул Октябрьская',
    'data': {
        'postal_code': '634534',
        'country': 'Россия',
        'region_fias_id': '889b1f3a-98aa-40fc-9d3d-0f41192758ab',
        'region_kladr_id': '7000000000000',
        'region_with_type': 'Томская обл',
        'region_type': 'обл',
        'region_type_full': 'область',
        'region': 'Томская',
        'area_fias_id': '3c033223-92b9-46a6-9b3c-e5bc7d178f79',
        'area_kladr_id': '7001700000000',
        'area_with_type': 'Томский р-н',
        'area_type': 'р-н',
        'area_type_full': 'район',
        'area': 'Томский',
        'city_fias_id': None,
        'city_kladr_id': None,
        'city_with_type': None,
        'city_type': None,
        'city_type_full': None,
        'city': None,
        'city_area': None,
        'city_district_fias_id': None,
        'city_district_kladr_id': None,
        'city_district_with_type': None,
        'city_district_type': None,
        'city_district_type_full': None,
        'city_district': None,
        'settlement_fias_id': 'c6b7c8de-5d2a-453a-88c8-ee4d7abe74f7',
        'settlement_kladr_id': '7001700014300',
        'settlement_with_type': 'село Турунтаево',
        'settlement_type': 'с',
        'settlement_type_full': 'село',
        'settlement': 'Турунтаево',
        'street_fias_id': 'a72ead02-ede3-4574-816f-ee9fd62cefcd',
        'street_kladr_id': '70017000143000800',
        'street_with_type': 'ул Октябрьская',
        'street_type': 'ул',
        'street_type_full': 'улица',
        'street': 'Октябрьская',
        'house_fias_id': None,
        'house_kladr_id': None,
        'house_type': None,
        'house_type_full': None,
        'house': None,
        'block_type': None,
        'block_type_full': None,
        'block': None,
        'flat_type': None,
        'flat_type_full': None,
        'flat': None,
        'flat_area': None,
        'square_meter_price': None,
        'flat_price': None,
        'postal_box': None,
        'fias_id': 'a72ead02-ede3-4574-816f-ee9fd62cefcd',
        'fias_code': None,
        'fias_level': '7',
        'fias_actuality_state': None,
        'kladr_id': '70017000143000800',
        'capital_marker': '4',
        'okato': '69254000115',
        'oktmo': '69654492101',
        'tax_office': '7014',
        'tax_office_legal': '7014',
        'timezone': None,
        'geo_lat': None,
        'geo_lon': None,
        'beltway_hit': None,
        'beltway_distance': None,
        'metro': None,
        'qc_geo': None,
        'qc_complete': None,
        'qc_house': None,
        'history_values': None,
        'unparsed_parts': None,
        'source': None,
        'qc': None
    }
}
#  Томская область, город Томск, Советский территориальный округ, Шевченко улица, 20
translate_result1 = 'томская область, город томск, шевченко улица, 20'
translate_result2 = 'томская область, томский район, турунтаево село, октябрьская улица'


class AddressTestCase(TestCase):
    def test_translate_dadata_object(self):
        from apps.addreses.utils import translate_dadata_object
        self.assertEqual(translate_result1, translate_dadata_object(suggestion1))
        self.assertEqual(translate_result2, translate_dadata_object(suggestion2))
